[package]
authors = [ "0xvpr <admin@0xvpr.io>" ]
name    = "concept"
version = "1.0.0"
edition = "2021"
publish = false
build   = "build.rs"

[dependencies]
winapi  = { version = "0.3.9", features = [ "fileapi", "winbase" ] }

[profile.release]
lto = true
