[package]
authors = [ "VPR <0xvpr@god.io>" ]
name    = "concept"
version = "1.0.0"
edition = "2021"
publish = false
build   = "build.rs"

[dependencies]
winapi = { version = "0.3.9", features = [ "libloaderapi", "processthreadsapi", "minwindef" ] }
libc = "*"

[profile.release]
lto = true

[build-dependencies]
winres = "0.1.12"
